### ISSUE TITLE
Error: read ECONNRESET

### ISSUE THREAD

**Issue by SearchAndDestroy** [jrudess/mfc_cb.node#10] opened 2017-04-10 22:10 UTC
I am getting this error and it can't reconnect.
Would it be possible to catch it and retry to reconnect?
`events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1026:11)
    at TCP.onread (net.js:569:26)`

**Comment by jrudess** [comment] 2017-04-13 02:30
Duplicate of #4

**Closed by jrudess** 2017-04-13 02:30 UTC
Labels: duplicate

**Comment by SearchAndDestroy** [comment] 2017-04-13 07:09
Not a duplicate since I a running only MFC and I use the other script for CB and it seems to happen when MFC is disconnected for too long.

**Comment by jrudess** [comment] 2017-04-14 03:36
Issue #4 is not CB specific.  It is general network connectivity killing the script.
